"""recreate employees table

Revision ID: 45ca6eb5fb95
Revises: 20260319_add_visit_invite_fields
Create Date: 2026-04-15 15:12:27.562433
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '45ca6eb5fb95'
down_revision = '20260319_add_visit_invite_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('is_current_employee', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('graduation', sa.String(), nullable=True),
    sa.Column('doj', sa.String(), nullable=True),
    sa.Column('expected_joining_date', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('project_lead', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=True)
    op.create_foreign_key(None, 'visitor_access_passes', 'employees', ['host_employee_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'employees', ['host_employee_id'], ['id'])
    op.drop_column('visits', 'approval_email_error')
    op.drop_column('visits', 'approval_email_sent')
    op.drop_column('visits', 'approval_email_last_attempt_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('approval_email_last_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('approval_email_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('approval_email_error', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visitor_access_passes', type_='foreignkey')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
